version: '3'
services:
  glance-eval-frontend:
    env_file: .env
    build: ./glance-eval/js/target/docker/
    restart: always
    depends_on:
      - glance-eval-backend
    ports:
      - "80:80"
  glance-eval-backend:
    env_file: .env
    build: ./glance-eval/jvm/target/docker/
    depends_on:
      - glance-eval-db
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xms512M -Xmx2G"
      GLANCE_DB_URL: "jdbc:postgresql://glance-eval-db:5432/"
  glance-eval-db:
    image: postgres:9.6.5
    ports:
      - "8003:5432"
    volumes:
      - ~/glance/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${GLANCE_DB_NAME}
      POSTGRES_USER: ${GLANCE_DB_USER}
      POSTGRES_PASSWORD: ${GLANCE_DB_PASS}
